---
language: node_js
node_js:
  - "8"
install:
  - yarn install --dev
script:
  - yarn run lint
  - yarn run build
  - '[ ! -z "${TRAVIS_TAG}" ] && yarn run package || true'
  - yarn run increment
deploy:
  provider: releases
  api_key: ${GITHUB_RELEASE_TOKEN}
  file:
    - county-wordpress-theme.zip
    - county-wordpress-theme.zip.sha256
  skip_cleanup: true
  on:
    tags: true
