version: 1
update_configs:
  - package_manager: "javascript"
    commit_message:
      prefix: "chore"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "php:composer"
    commit_message:
      prefix: "chore"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
